name: Deploy Storybook to Chromatic

on:
  push:
    branches: [main]
  pull_request:

jobs:
  chromatic-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.19.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Publish to Chromatic
        run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }}
